; This file is for the FamiTone2 library and was generated by FamiStudio

FT_DPCM_PTR=$C000
.export _abertura=abertura

abertura:
	.byte 1
	.word @instruments
	.word @samples-3
; 00 : Song 1
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 307,256

.export abertura
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.byte $b0 ; 00 : Acoustic Grand Piano
	.word @env0, @env1, @env1
	.byte $00

@env0:
	.byte $cf,$7f,$00,$00
@env1:
	.byte $c0,$7f,$00,$01

@samples:

@song0ch0:
	.byte $fb, $01
@song0ch0loop:
	.byte $83, $80, $3c, $93, $16, $46, $a7, $00, $8b, $46, $a1, $4a, $91, $4e, $a7, $00, $8b, $46, $b5, $46, $a7, $00, $8b, $46
	.byte $a1, $4a, $91, $54, $d1, $8d, $00, $89, $16, $46, $dd, $00, $8b, $12, $4e, $df, $00, $89, $0e, $b5, $46, $a5, $4a, $8d
	.byte $0c, $4c, $a5, $00, $8b, $46, $9b, $8b, $00, $8b, $08, $38, $8b, $01, $3c, $87, $00, $85, $3e, $8f, $0c, $50, $8b, $01
	.byte $54, $87, $00, $85, $56, $8f, $2e, $5e, $b3, $18, $60, $b3, $32, $62, $f9, $9b, $00, $a9
@song0ref94:
	.byte $f9, $f9, $f9, $d1, $f9, $f9, $f9, $d1, $f9, $f9, $f9, $d1, $f9, $f9, $f9, $d1, $f9, $f9, $f9, $d1, $fd
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $ff, $14
	.word @song0ref94
	.byte $ff, $0c
	.word @song0ref94
	.byte $fd
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $ff, $14
	.word @song0ref94
	.byte $ff, $0c
	.word @song0ref94
	.byte $fd
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $ff, $14
	.word @song0ref94
	.byte $ff, $0c
	.word @song0ref94
	.byte $fd
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $ff, $14
	.word @song0ref94
	.byte $ff, $0c
	.word @song0ref94
	.byte $fd
	.word @song0ch4loop
