; This file is for the FamiTone2 library and was generated by FamiStudio
; Required flags for Untitled:

.export _musicas:=musicas

musicas:
	.byte 3
	.word @instruments
	.word @samples-3
; 00 : fifa
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 307,256
; 01 : globo
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	.word 307,256
; 02 : hino
	.word @song2ch0
	.word @song2ch1
	.word @song2ch2
	.word @song2ch3
	.word @song2ch4
	.word 307,256

.export musicas
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.byte $70 ; 00 : Acoustic Grand Piano
	.word @env0, @env1, @env1
	.byte $00
	.byte $b0 ; 01 : Instrument 1
	.word @env0, @env1, @env1
	.byte $00

@env0:
	.byte $c9,$7f,$00,$00
@env1:
	.byte $c0,$7f,$00,$01

@samples:

@song0ch0:
	.byte $fb, $01
@song0ch0loop:
@song0ref4:
	.byte $f9, $f9, $f9, $d1, $f9, $f9, $f9, $d1, $f9, $f9, $f9, $d1, $f9, $f9, $f9, $d1
	.byte $ff, $10
	.word @song0ref4
	.byte $fd
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $80, $54, $a7, $00, $8b, $54, $99, $00, $85, $58, $91, $5c, $b5, $54, $b3, $24, $54, $a7, $00, $8b, $54, $8b, $01, $58
	.byte $8f, $5c, $8f, $1a, $58, $d9, $4a, $8f, $24, $54, $b5, $54, $a1, $58, $91, $5c, $b5, $54, $b3, $62, $54, $b3, $6a, $54
	.byte $8f, $4e, $8f, $58, $8f, $7a, $4a, $d1, $00, $85, $4a, $8f, $24, $54, $a7, $00, $8b, $54, $9b, $00, $83, $58, $91, $5c
	.byte $ab, $00, $87, $54, $ab, $00, $85, $24, $54, $ad, $00, $85, $54, $8f, $5e, $8d, $00, $5c, $89, $00, $83, $1a, $58, $b3
	.byte $16, $91, $5c, $8f, $5e, $8b, $01, $14, $7a, $b3, $1e, $91, $5c, $8f, $54, $8f, $76, $5e, $89, $00, $83, $5c, $8f, $54
	.byte $8f, $1a, $58, $89, $00, $83, $54, $8f, $52, $8f, $0c, $91, $6a, $91, $6c, $8f, $00, $6c, $89, $01, $6a, $91, $6c, $91
	.byte $6c, $8b, $00, $6a, $89, $00, $85, $6c, $8f, $6c, $8d, $00, $6a, $8b, $00, $83, $6c, $8f, $81, $6c, $8d, $6a, $8b, $00
	.byte $83, $6c, $91, $6c, $8d, $6a, $8d, $01, $6c, $8d, $0d, $6c, $8d, $0c, $6a, $8b, $00, $0d, $6c, $85, $00, $83, $70, $8f
	.byte $74, $91, $70, $8b, $01, $24, $6c, $b1, $00, $24, $6c, $95, $00, $89, $70, $8d, $00, $1e, $74, $b3, $1e, $6c, $a1, $1a
	.byte $8f, $16, $6c, $a7, $00, $89, $16, $6c, $8b, $01, $70, $8f, $74, $8f, $1a, $70, $b3, $1a, $9d, $00, $83, $62, $8f, $24
	.byte $6c, $ab, $00, $85, $24, $6c, $9d, $01, $70, $8f, $1e, $74, $ad, $00, $83, $1e, $6c, $a1, $1a, $8b, $01, $18, $6c, $af
	.byte $01, $10, $6c, $8f, $66, $8f, $70, $8d, $00, $1a, $62, $cf, $00, $87, $62, $8f, $24, $6c, $b3, $24, $6c, $99, $00, $85
	.byte $70, $8f, $1e, $74, $b3, $1e, $6c, $a1, $1a, $85, $00, $87, $16, $6c, $a9, $00, $87, $16, $6c, $8f, $76, $8b, $01, $74
	.byte $8f, $1a, $70, $b3, $16, $91, $74, $8d, $00, $76, $89, $00, $83, $14, $62, $af, $00, $f9, $b1, $fd
	.word @song0ch1loop
@song0ch4:
@song0ch3:
@song0ch2:
@song0ch2loop:
	.byte $ff, $10
	.word @song0ref4
	.byte $ff, $10
	.word @song0ref4
	.byte $fd
	.word @song0ch2loop
@song1ch0:
	.byte $fb, $01
@song1ch0loop:
	.byte $82, $40
@song1ref6:
	.byte $99, $44, $99, $48, $99, $4a, $99, $4e, $99
@song1ref15:
	.byte $4a, $99, $52, $99, $4a, $99, $44, $99, $40, $d1, $52, $99, $54, $99, $58
	.byte $ff, $0b
	.word @song1ref6
	.byte $48, $99, $46, $99, $44, $b5, $f9, $83, $00, $8b, $54, $b5, $5c, $99, $44, $99, $54, $99, $5c, $99, $52, $99, $4e, $99
	.byte $4c, $99, $52, $99, $4e, $99, $a9, $00, $8b, $4e, $b5, $4a, $99, $44, $99, $48, $b5, $58, $99, $50, $99, $5c, $99, $00
	.byte $8b, $5c, $8b, $58, $8b, $00, $8b, $58, $99, $52, $99, $58, $99, $a9, $52, $99, $54, $99, $58
	.byte $ff, $08
	.word @song1ref6
	.byte $8b, $8d
	.byte $ff, $09
	.word @song1ref15
	.byte $df, $a9, $00, $8b, $4a, $99, $48, $99, $46, $99
@song1ref118:
	.byte $4a, $99, $4e, $99, $52, $99, $4e, $99, $4a, $99, $54, $99, $52, $99, $5c, $ed, $c5, $00, $8b, $52, $99, $4a, $99, $00
	.byte $8b, $4a, $8b, $48, $8b, $00, $8b, $60, $99, $00, $8b, $48, $8b, $5c, $99, $58, $a7, $00, $8b, $58, $99, $54, $d1, $52
	.byte $99, $00, $8b, $52, $b5, $4e, $99, $4c, $99, $4e, $99, $5c, $99, $58, $8b, $8d, $4e, $99, $4a, $b5, $00, $8b
@song1ref188:
	.byte $58, $b5, $52, $b5, $58, $99, $52, $d1
	.byte $ff, $0a
	.word @song1ref118
	.byte $52, $d1
	.byte $ff, $08
	.word @song1ref188
	.byte $ff, $0a
	.word @song1ref118
	.byte $4e, $8b, $54, $b5, $5c, $99, $00, $8b
@song1ref215:
	.byte $5c, $b5, $54, $99, $9b, $5c, $99, $54, $d1, $4e, $99, $52, $99, $54, $99, $58, $99, $5c, $99, $60, $99, $5c, $b5, $52
	.byte $99, $5c, $b5, $8d, $00, $8b, $5c, $b5, $58, $99, $54, $99, $52, $99, $00, $8b, $52, $99, $4e, $8b, $8d, $58, $b5, $4a
	.byte $b5
@song1ref264:
	.byte $58, $b5, $52, $a7, $8d, $58, $99, $52, $d1, $4a, $99, $4e, $99, $52, $99, $4e, $8b, $8d, $4a, $99, $52, $d1
	.byte $ff, $14
	.word @song1ref264
	.byte $4e, $8b, $54, $d1
	.byte $ff, $1a
	.word @song1ref215
	.byte $a7, $00, $8b, $5c, $a7, $00, $8b, $5c, $a7, $58, $99, $54, $8b, $52, $a7, $00, $8b, $52, $99, $4e, $99, $58, $b5, $4a
	.byte $ed, $00, $99, $f9, $e5, $fd
	.word @song1ch0loop
@song1ch4:
@song1ch3:
@song1ch2:
@song1ch1:
@song1ch1loop:
@song1ref332:
	.byte $f9, $e5, $f9, $e5, $f9, $e5, $f9, $e5
	.byte $ff, $08
	.word @song1ref332
	.byte $ff, $08
	.word @song1ref332
	.byte $ff, $08
	.word @song1ref332
	.byte $ff, $08
	.word @song1ref332
	.byte $ff, $08
	.word @song1ref332
	.byte $ff, $08
	.word @song1ref332
	.byte $ff, $08
	.word @song1ref332
	.byte $fd
	.word @song1ch1loop
@song2ch0:
	.byte $fb, $01
@song2ch0loop:
	.byte $82, $44, $8d, $00, $8d, $44, $8d, $00, $8d, $46, $8d, $00, $8d, $4a, $9d, $00, $9d, $4a, $8d, $00, $8d, $4e, $8d, $00
	.byte $8d, $52
@song2ref30:
	.byte $9d, $00, $9d, $52, $8d, $00, $8d, $54, $8d, $00, $8d, $5e, $9d, $00, $9d, $5c, $bd, $00, $9d, $9f, $58, $8d, $00, $8d
	.byte $52
@song2ref55:
	.byte $8d, $00, $8d, $58, $9d, $00, $9d, $54
@song2ref63:
	.byte $8d, $00, $8d, $52, $8d, $00, $8d, $4e, $9d, $00, $9d, $4a
	.byte $ff, $0b
	.word @song2ref63
	.byte $4e, $9d, $00, $9d, $26, $9d, $00, $9d, $46, $8d, $00, $8d, $4a, $8d, $00, $8d, $4e
	.byte $ff, $0b
	.word @song2ref30
	.byte $52, $9d, $00, $8d, $56, $8d, $00, $8d, $58, $8d, $00, $8d, $5c, $8d, $00, $8d, $62, $9d, $00, $9d, $5e, $bd, $00, $8d
	.byte $9f, $5e, $8d, $00, $8d, $58, $8d, $00, $8d, $62, $9d, $00, $9d, $5e, $8d, $00, $8d, $58, $8d, $00, $8d, $52, $8d, $00
	.byte $8d, $4e, $8d, $00, $8d, $4a, $8d, $00, $8d, $44, $9d, $00, $9d, $5c, $bd, $00, $9d, $4a, $9d, $00, $9d, $62, $9d, $00
	.byte $9d, $5e, $8d, $00, $8d, $5c
	.byte $ff, $0b
	.word @song2ref55
	.byte $5c, $8d, $00, $8d, $58, $9d, $00, $9d, $58, $ad, $00, $ad
@song2ref191:
	.byte $5e, $8d, $00, $8d, $5c, $8d, $00, $8d, $58, $9d, $00, $9d
	.byte $ff, $0c
	.word @song2ref191
	.byte $5e, $8d, $00, $8d, $5c, $8d, $00, $8d, $52, $bd, $00, $9d, $52, $8d, $00, $8d, $54
	.byte $ff, $0b
	.word @song2ref55
	.byte $58, $8d, $00, $8d, $5c, $9d, $00, $9d
@song2ref234:
	.byte $58, $8d, $00, $8d, $5c, $8d, $00, $8d, $5e, $9d, $00, $9d, $62, $8d, $00, $8d, $64, $8d, $00, $8d, $70, $9d, $00, $9d
	.byte $54, $9d, $00, $9d, $5c, $9d, $00, $9d, $58, $9d, $00, $9d, $54, $bd, $00, $bd
@song2ref274:
	.byte $4e, $9d, $00, $9d, $46, $9d, $8f, $00, $ad
@song2ref283:
	.byte $54, $8d, $00, $8d, $4e, $8d, $00, $8d, $46, $8d, $00, $8d, $5c, $9d, $00, $9d, $4a, $9d, $bf, $00, $dd, $4e, $9d, $00
	.byte $9d, $54, $8d, $00, $8d, $5e, $8d, $00, $8d, $54, $8d, $00, $8d
	.byte $ff, $0c
	.word @song2ref283
	.byte $4a, $9d, $00, $9d, $4a, $9d, $9f, $00, $bd, $54, $9d, $00, $9d, $4e, $9d, $00, $9d, $62, $9d, $00, $9d, $68, $9d, $00
	.byte $9d, $68, $9d, $00, $9d, $4e, $bd, $00, $9d, $9f, $4a, $9d, $00, $9d, $54, $9d, $00, $9d
	.byte $ff, $2e
	.word @song2ref274
	.byte $ff, $0c
	.word @song2ref283
	.byte $4a, $9d, $00, $9d, $4a, $9d, $9f, $00, $ad, $54, $9d, $00, $9d, $58, $9d, $00, $8d
	.byte $ff, $0c
	.word @song2ref234
	.byte $58, $8d, $00, $8d, $5e, $bd, $00, $bd, $4e, $9d, $00, $9d, $54, $9d, $00, $9d, $4a, $9d, $00, $9d, $4a, $ad, $00, $9d
	.byte $62, $8d, $00, $8d, $5e, $8d, $00, $8d, $4a, $8d, $00, $8d, $4e, $bd, $00, $bd, $5e, $9d, $00, $8d, $8f, $54, $8d, $00
	.byte $8d, $54, $8d, $00, $9d, $58, $9d, $00, $9d, $58, $9d, $00, $9d, $5c, $9d, $00, $9d, $5e, $f9, $a3, $00, $bd, $f9, $f9
	.byte $8b, $f9, $f9, $8b, $fd
	.word @song2ch0loop
@song2ch4:
@song2ch3:
@song2ch1:
@song2ch1loop:
@song2ref473:
	.byte $f9, $f9, $8b, $f9, $f9, $8b, $f9, $f9, $8b, $f9, $f9, $8b
	.byte $ff, $0c
	.word @song2ref473
	.byte $ff, $0c
	.word @song2ref473
	.byte $ff, $0c
	.word @song2ref473
	.byte $ff, $0c
	.word @song2ref473
	.byte $ff, $0c
	.word @song2ref473
	.byte $ff, $0c
	.word @song2ref473
	.byte $ff, $0c
	.word @song2ref473
	.byte $fd
	.word @song2ch1loop
@song2ch2:
@song2ch2loop:
	.byte $82
@song2ref511:
	.byte $3c, $9d, $00, $9d, $32, $9d, $00, $9d, $3c, $9d, $00, $9d, $32, $9d, $00, $9d
	.byte $ff, $10
	.word @song2ref511
	.byte $ff, $10
	.word @song2ref511
	.byte $ff, $10
	.word @song2ref511
	.byte $ff, $10
	.word @song2ref511
	.byte $ff, $10
	.word @song2ref511
	.byte $ff, $10
	.word @song2ref511
	.byte $ff, $10
	.word @song2ref511
	.byte $ff, $10
	.word @song2ref511
	.byte $ff, $10
	.word @song2ref511
	.byte $ff, $10
	.word @song2ref511
	.byte $ff, $10
	.word @song2ref511
	.byte $ff, $10
	.word @song2ref511
	.byte $ff, $10
	.word @song2ref511
	.byte $ff, $10
	.word @song2ref511
	.byte $ff, $10
	.word @song2ref511
	.byte $ff, $10
	.word @song2ref511
	.byte $ff, $10
	.word @song2ref511
	.byte $ff, $10
	.word @song2ref511
	.byte $ff, $10
	.word @song2ref511
	.byte $ff, $10
	.word @song2ref511
	.byte $ff, $10
	.word @song2ref511
	.byte $ff, $10
	.word @song2ref511
	.byte $ff, $10
	.word @song2ref511
	.byte $ff, $10
	.word @song2ref511
	.byte $ff, $10
	.word @song2ref511
	.byte $ff, $10
	.word @song2ref511
	.byte $ff, $10
	.word @song2ref511
	.byte $ff, $10
	.word @song2ref511
	.byte $8f, $3c, $9d, $00, $9d, $3c, $9d, $00, $f9, $93, $f9, $f9, $8b, $f9, $f9, $8b, $fd
	.word @song2ch2loop

