; This file is for the FamiTone2 library and was generated by FamiStudio

.export _hino=hino

hino:
	.byte 1
	.word @instruments
	.word @samples-3
; 00 : Song 1
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 307,256

.export hino
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.byte $b0 ; 00 : Instrument 1
	.word @env0, @env1, @env1
	.byte $00

@env0:
	.byte $cf,$7f,$00,$00
@env1:
	.byte $c0,$7f,$00,$01

@samples:

@song0ch0:
	.byte $fb, $01
@song0ch0loop:
	.byte $80, $44, $8d, $00, $8d, $44, $8d, $00, $8d, $46, $8d, $00, $8d, $4a, $9d, $00, $9d, $4a, $8d, $00, $8d, $4e, $8d, $00
	.byte $8d, $52, $9d, $00, $9d, $52, $8d, $00, $8d, $54, $8d, $00, $8d, $5e, $9d, $00, $9d, $5c, $bd, $00, $9d, $9f, $58, $8d
	.byte $00, $8d, $52, $8d, $00, $8d, $58, $9d, $00, $9d, $54, $8d, $00, $8d, $52, $8d, $00, $8d, $4e, $9d, $00, $9d, $4a, $8d
	.byte $00, $8d, $52, $8d, $00, $8d, $4e, $9d, $00, $9d, $4e, $9d, $00, $9d, $26, $9d, $00, $9d, $46, $8d, $00, $8d, $4a, $8d
	.byte $00, $8d, $4e, $9d, $00, $9d, $52, $8d, $00, $8d, $54, $8d, $00, $8d, $52, $9d, $00, $8d, $56, $8d, $00, $8d, $58, $8d
	.byte $00, $8d, $5c, $8d, $00, $8d, $62, $9d, $00, $9d, $5e, $bd, $00, $8d, $9f, $5e, $8d, $00, $8d, $58, $8d, $00, $8d, $62
	.byte $9d, $00, $9d, $5e, $8d, $00, $8d, $58, $8d, $00, $8d, $52, $8d, $00, $8d, $4e, $8d, $00, $8d, $4a, $8d, $00, $8d, $44
	.byte $9d, $00, $9d, $5c, $bd, $00, $9d, $4a, $9d, $00, $9d, $62, $9d, $00, $9d, $5e, $8d, $00, $8d, $5c, $8d, $00, $8d, $58
	.byte $9d, $00, $9d, $54, $8d, $00, $8d, $5c, $8d, $00, $8d, $58, $9d, $00, $9d, $58, $ad, $00, $ad, $5e, $8d, $00, $8d, $5c
	.byte $8d, $00, $8d, $58, $9d, $00, $9d, $5e, $8d, $00, $8d, $5c, $8d, $00, $8d, $58, $9d, $00, $9d, $5e, $8d, $00, $8d, $5c
	.byte $8d, $00, $8d, $52, $bd, $00, $9d, $52, $8d, $00, $8d, $54, $8d, $00, $8d, $58, $9d, $00, $9d, $54, $8d, $00, $8d, $58
	.byte $8d, $00, $8d, $5c, $9d, $00, $9d, $58, $8d, $00, $8d, $5c, $8d, $00, $8d, $5e, $9d, $00, $9d, $62, $8d, $00, $8d, $64
	.byte $8d, $00, $8d, $70, $9d, $00, $9d, $54, $9d, $00, $9d, $5c, $9d, $00, $9d, $58, $9d, $00, $9d, $54, $bd, $00, $bd
@song0ref315:
	.byte $4e, $9d, $00, $9d, $46, $9d, $8f, $00, $ad, $54, $8d, $00, $8d, $4e, $8d, $00, $8d, $46, $8d, $00, $8d, $5c, $9d, $00
	.byte $9d, $4a, $9d, $bf, $00, $dd, $4e, $9d, $00, $9d, $54, $8d, $00, $8d, $5e, $8d, $00, $8d, $54, $8d, $00, $8d, $54, $8d
	.byte $00, $8d, $4e, $8d, $00, $8d, $46, $8d, $00, $8d, $4a, $9d, $00, $9d, $4a, $9d, $9f, $00, $bd, $54, $9d, $00, $9d, $4e
	.byte $9d, $00, $9d, $62, $9d, $00, $9d, $68, $9d, $00, $9d, $68, $9d, $00, $9d, $4e, $bd, $00, $9d, $9f, $4a, $9d, $00, $9d
	.byte $54, $9d, $00, $9d
	.byte $ff, $42
	.word @song0ref315
	.byte $ad, $54, $9d, $00, $9d, $58, $9d, $00, $8d, $58, $8d, $00, $8d, $5c, $8d, $00, $8d, $5e, $9d, $00, $9d, $58, $8d, $00
	.byte $8d, $5e, $bd, $00, $bd, $4e, $9d, $00, $9d, $54, $9d, $00, $9d, $4a, $9d, $00, $9d, $4a, $ad, $00, $9d, $62, $8d, $00
	.byte $8d, $5e, $8d, $00, $8d, $4a, $8d, $00, $8d, $4e, $bd, $00, $bd, $5e, $9d, $00, $8d, $8f, $54, $8d, $00, $8d, $54, $8d
	.byte $00, $9d, $58, $9d, $00, $9d, $58, $9d, $00, $9d, $5c, $9d, $00, $9d, $5e, $f9, $a3, $00, $bd, $f9, $f9, $8b, $f9, $f9
	.byte $8b, $fd
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
@song0ref519:
	.byte $f9, $f9, $8b, $f9, $f9, $8b, $f9, $f9, $8b, $f9, $f9, $8b, $f9, $f9, $8b, $f9, $f9, $8b, $f9, $f9, $8b, $f9, $f9, $8b
	.byte $ff, $18
	.word @song0ref519
	.byte $ff, $18
	.word @song0ref519
	.byte $ff, $18
	.word @song0ref519
	.byte $fd
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $80
@song0ref557:
	.byte $3c, $9d, $00, $9d, $32, $9d, $00, $9d, $3c, $9d, $00, $9d, $32, $9d, $00, $9d, $3c, $9d, $00, $9d, $32, $9d, $00, $9d
	.byte $ff, $18
	.word @song0ref557
	.byte $ff, $18
	.word @song0ref557
	.byte $ff, $18
	.word @song0ref557
	.byte $ff, $18
	.word @song0ref557
	.byte $ff, $18
	.word @song0ref557
	.byte $ff, $18
	.word @song0ref557
	.byte $ff, $18
	.word @song0ref557
	.byte $ff, $18
	.word @song0ref557
	.byte $ff, $18
	.word @song0ref557
	.byte $ff, $18
	.word @song0ref557
	.byte $ff, $18
	.word @song0ref557
	.byte $ff, $18
	.word @song0ref557
	.byte $ff, $18
	.word @song0ref557
	.byte $ff, $18
	.word @song0ref557
	.byte $ff, $18
	.word @song0ref557
	.byte $ff, $18
	.word @song0ref557
	.byte $ff, $18
	.word @song0ref557
	.byte $ff, $18
	.word @song0ref557
	.byte $3c, $9d, $00, $9d, $32, $9d, $00, $9d, $8f, $3c, $9d, $00, $9d, $3c, $9d, $00, $f9, $93, $f9, $f9, $8b, $f9, $f9, $8b
	.byte $fd
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $ff, $18
	.word @song0ref519
	.byte $ff, $18
	.word @song0ref519
	.byte $ff, $18
	.word @song0ref519
	.byte $ff, $18
	.word @song0ref519
	.byte $fd
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $ff, $18
	.word @song0ref519
	.byte $ff, $18
	.word @song0ref519
	.byte $ff, $18
	.word @song0ref519
	.byte $ff, $18
	.word @song0ref519
	.byte $fd
	.word @song0ch4loop

