; This file is for the FamiTone2 library and was generated by FamiStudio

FT_DPCM_PTR=$C000
.export _trilha_fifa=trilha_fifa

trilha_fifa:
	.byte 1
	.word @instruments
	.word @samples-3
; 00 : Song 1
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 307,256

.export trilha_fifa
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.byte $70 ; 00 : Acoustic Grand Piano
	.word @env0, @env1, @env1
	.byte $00

@env0:
	.byte $cf,$7f,$00,$00
@env1:
	.byte $c0,$7f,$00,$01

@samples:

@song0ch0:
	.byte $fb, $01
@song0ch0loop:
@song0ref4:
	.byte $f9, $f9, $f9, $d1, $f9, $f9, $f9, $d1, $f9, $f9, $f9, $d1, $f9, $f9, $f9, $d1, $f9, $f9, $f9, $d1, $f9, $f9, $f9, $d1
	.byte $f9, $f9, $f9, $d1, $f9, $f9, $f9, $d1, $fd
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $80, $54, $a7, $00, $8b, $54, $99, $00, $85, $58, $91, $5c, $b5, $54, $b3, $24, $54, $a7, $00, $8b, $54, $8b, $01, $58
	.byte $8f, $5c, $8f, $1a, $58, $d9, $4a, $8f, $24, $54, $b5, $54, $a1, $58, $91, $5c, $b5, $54, $b3, $62, $54, $b3, $6a, $54
	.byte $8f, $4e, $8f, $58, $8f, $7a, $4a, $d1, $00, $85, $4a, $8f, $24, $54, $a7, $00, $8b, $54, $9b, $00, $83, $58, $91, $5c
	.byte $ab, $00, $87, $54, $ab, $00, $85, $24, $54, $ad, $00, $85, $54, $8f, $5e, $8d, $00, $5c, $89, $00, $83, $1a, $58, $b3
	.byte $16, $91, $5c, $8f, $5e, $8b, $01, $14, $7a, $b3, $1e, $91, $5c, $8f, $54, $8f, $76, $5e, $89, $00, $83, $5c, $8f, $54
	.byte $8f, $1a, $58, $89, $00, $83, $54, $8f, $52, $8f, $0c, $91, $6a, $91, $6c, $8f, $00, $6c, $89, $01, $6a, $91, $6c, $91
	.byte $6c, $8b, $00, $6a, $89, $00, $85, $6c, $8f, $6c, $8d, $00, $6a, $8b, $00, $83, $6c, $8f, $81, $6c, $8d, $6a, $8b, $00
	.byte $83, $6c, $91, $6c, $8d, $6a, $8d, $01, $6c, $8d, $0d, $6c, $8d, $0c, $6a, $8b, $00, $0d, $6c, $85, $00, $83, $70, $8f
	.byte $74, $91, $70, $8b, $01, $24, $6c, $b1, $00, $24, $6c, $95, $00, $89, $70, $8d, $00, $1e, $74, $b3, $1e, $6c, $a1, $1a
	.byte $8f, $16, $6c, $a7, $00, $89, $16, $6c, $8b, $01, $70, $8f, $74, $8f, $1a, $70, $b3, $1a, $9d, $00, $83, $62, $8f, $24
	.byte $6c, $ab, $00, $85, $24, $6c, $9d, $01, $70, $8f, $1e, $74, $ad, $00, $83, $1e, $6c, $a1, $1a, $8b, $01, $18, $6c, $af
	.byte $01, $10, $6c, $8f, $66, $8f, $70, $8d, $00, $1a, $62, $cf, $00, $87, $62, $8f, $24, $6c, $b3, $24, $6c, $99, $00, $85
	.byte $70, $8f, $1e, $74, $b3, $1e, $6c, $a1, $1a, $85, $00, $87, $16, $6c, $a9, $00, $87, $16, $6c, $8f, $76, $8b, $01, $74
	.byte $8f, $1a, $70, $b3, $16, $91, $74, $8d, $00, $76, $89, $00, $83, $14, $62, $af, $00, $f9, $b1, $fd
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $ff, $20
	.word @song0ref4
	.byte $fd
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $ff, $20
	.word @song0ref4
	.byte $fd
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $ff, $20
	.word @song0ref4
	.byte $fd
	.word @song0ch4loop
